repos:
  - repo: local
    hooks:
      - id: prettier-format
        name: Prettier Format
        language: system
        entry: npx prettier --write .
        pass_filenames: false
        types:
          - ts
        files: \.(ts|js)x?$

      - id: eslint-lint
        name: ESLint Lint
        language: system
        entry: npx eslint --fix .
        pass_filenames: false
        types:
          - ts
        files: \.(ts|js)x?$
